services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/logs
    networks:
      - app_network

  loki:
    image: grafana/loki:latest-amd64
    container_name: loki
    ports:
      - "${LOKI_PORT}:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app_network


  promtail:
    image: grafana/promtail:latest-amd64
    container_name: promtail
    depends_on:
      - loki
    volumes:
      - ./logs:/logs
      - ./prometheus/promtail-config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - prometheus
      - loki
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_DATASOURCES_DEFAULT_DATASOURCE_NAME: Loki
      GF_INSTALL_PLUGINS: marcusolsson-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/logs
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - app_network

volumes:
  grafana_data:

networks:
  app_network:
    external: true
    name: ${CDC_NETWORK_NAME}