services:
  #####################
  # DATABASES + PGAdmin
  #####################

  db_legacy:
    image: postgres:16.11
    container_name: postgres_db_legacy
    restart: always
    ports:
      - "${POSTGRES_LEGACY_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_LEGACY_USER}
      POSTGRES_PASSWORD: ${POSTGRES_LEGACY_PASSWORD}
      POSTGRES_DB: legacy
    volumes:
      - ./pgdata_first:/var/lib/postgresql/data
      - ./db/legacy/init:/docker-entrypoint-initdb.d:ro
      - ./shared_logs:/shared/logs
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_wal_senders=10"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_LEGACY_USER} -d legacy" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_network

  db_clean:
    image: postgis/postgis:16-3.4
    container_name: postgres_db_clean
    restart: always
    ports:
      - "${POSTGRES_CLEAN_PORTS}"
    environment:
      POSTGRES_USER: ${POSTGRES_CLEAN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_CLEAN_PASSWORD}
      POSTGRES_DB: clean
    volumes:
      - ./pgdata_second:/var/lib/postgresql/data
      - ./db/clean/init:/docker-entrypoint-initdb.d:ro
      - ./shared_logs:/shared/logs
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_CLEAN_USER} -d clean" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:9.12
    container_name: pgadmin_panel_web
    restart: always
    ports:
      - "${PGADMIN_PORTS}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app_network

##########################
# KAFKA + KAFDROP + CONNECT
##########################

  kafka:
    image: bashj79/kafka-kraft:latest
    container_name: kafka
    restart: always
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:${KAFKA_INTERNAL_PORT},CONTROLLER://0.0.0.0:${KAFKA_CONTROLLER_PORT}"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${KAFKA_ADVERTISED_HOST}:${KAFKA_INTERNAL_PORT}"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "${KAFKA_AUTO_CREATE_TOPICS_ENABLE}"
      KAFKA_MESSAGE_MAX_BYTES: 200000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 200000000
    volumes:
      - kafka_data:/tmp/kraft-combined-logs
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "cd /opt/kafka/bin && sh kafka-topics.sh --bootstrap-server localhost:${KAFKA_PORT} --list >/dev/null 2>&1 || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      db_legacy:
        condition: service_healthy
      db_clean:
        condition: service_healthy
    networks:
      - app_network

  kafdrop:
    image: obsidiandynamics/kafdrop:4.2.0
    build:
      context: .
      dockerfile: kafdrop/Dockerfile
    restart: always
    ports:
      - "${KAFDROP_PORT}:9000"
    environment:
      KAFKA_BROKERCONNECT: "${KAFKA_BROKERCONNECT}"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app_network

  connect:
    image: debezium/connect:2.7.3.Final
    container_name: my-connect
    restart: always
    ports:
      - "${CONNECT_PORT}:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_PLUGIN_PATH: /kafka/connect
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - connect-data:/kafka/connect
    networks:
      - app_network

  init-connector:
    build:
      context: .
      dockerfile: kafdrop/Dockerfile.connect
    volumes:
      - ./scripts:/scripts
      - ./connector:/connector
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app_network

  init-sink:
    build:
      context: .
      dockerfile: kafdrop/Dockerfile.sink
    volumes:
      - ./scripts:/scripts
      - ./connector:/connector
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app_network

  init-topics:
    build:
      context: .
      dockerfile: kafdrop/Dockerfile.topics
    volumes:
      - ./scripts:/scripts
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app_network


volumes:
  pgadmin-data:
  kafka_data:
  connect-plugins:
  connect-data:


networks:
  app_network:
    name: ${CDC_NETWORK_NAME}