services:
  api_app:
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file:
        - .env
    container_name: faker_app
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shared_logs:/shared/logs
    networks:
      - app_network

networks:
  app_network:
    external: true
    name: cdc_network