services:
  api_app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: faker_app
    ports:
      - "${FAST_API_PORT}:8000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/logs
    environment:
      POSTGRES_LEGACY_USER: ${POSTGRES_LEGACY_USER}
      POSTGRES_LEGACY_PASSWORD: ${POSTGRES_LEGACY_PASSWORD}
      POSTGRES_CLEAN_USER: ${POSTGRES_CLEAN_USER}
      POSTGRES_CLEAN_PASSWORD: ${POSTGRES_CLEAN_PASSWORD}
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app_network
