services:
  kafka:
    image: bashj79/kafka-kraft:latest
    container_name: kafka2
    restart: always
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_MESSAGE_MAX_BYTES: 200000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 200000000
      # KAFKA_DATA_DIR можно вообще убрать, толку от него нет
    volumes:
      - kafka_data:/tmp/kraft-combined-logs
    networks:
      - app_network


  kafdrop:
    container_name: kafdrop2
    build:
      context: .
      dockerfile: kafdrop/Dockerfile
    restart: always
    ports:
      - "${KAFDROP_PORT}:${KAFDROP_PORT}"
    environment:
      KAFKA_BROKERCONNECT: "${KAFKA_BROKERCONNECT}"
      JVM_OPTS: "-Xms128M -Xmx512M"
    entrypoint: [ "./wait-for-it.sh", "kafka:9092", "--" ]
    command: [ "java", "-jar", "kafdrop.jar" ]
    networks:
      - app_network

  connect:
    image: debezium/connect:2.7.3.Final
    container_name: my-connect
    restart: always
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: connect

      CONNECT_PLUGIN_PATH: /kafka/connect
    depends_on:
      - kafka
    volumes:
      - connect-data:/kafka/connect
    networks:
      - app_network


  init-connector:
    build:
      context: .
      dockerfile: kafdrop/Dockerfile.connect
    volumes:
      - ./scripts:/scripts
      - ./connector:/connector
    networks:
      - app_network

  init-sink:
    build:
      context: .
      dockerfile: kafdrop/Dockerfile.sink
    volumes:
      - ./scripts:/scripts
      - ./connector:/connector
    networks:
      - app_network


  init-topics:
    build:
      context: .
      dockerfile: kafdrop/Dockerfile.topics
    volumes:
      - ./scripts:/scripts
    networks:
      - app_network


networks:
  app_network:
    external: true
    name: cdc_network

volumes:
  kafka_data:
  connect-plugins:
  connect-data: