{
 "title": "Statistic Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Customers count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (component) (\n  rate(\n    ({job=\"file-logs\"} | json | component=\"auto_generator\"\n     | unwrap customers_count\n    )[1m]\n  )\n)"
    }
   ]
  },
  {
   "title": "Orders count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (component) (\n  rate(\n    ({job=\"file-logs\"} | json | component=\"auto_generator\"\n     | unwrap orders_count\n    )[1m]\n  )\n)"
    }
   ]
  },
  {
   "title": "Manage Legacy Data logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"file-logs\"} | json | component=\"legacy_data\""
    }
   ]
  },
  {
   "title": "Kafka Consumer logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"file-logs\"} | json | component=\"kafka_consumer\""
    }
   ]
  },
  {
   "title": "Faker logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"file-logs\"} | json | component=\"auto_generator\""
    }
   ]
  }
 ]
}