FROM python:3.11-slim

WORKDIR /app

COPY . /app
COPY scripts/wait-for-it.sh ./wait-for-it.sh

RUN apt-get update && \
    apt-get install -y netcat-openbsd && \
    pip install --no-cache-dir sqlalchemy psycopg2-binary && \
    rm -rf /var/lib/apt/lists/*

RUN chmod +x ./wait-for-it.sh

CMD ["./wait-for-it.sh", "db_clean:5432", "clean", "--", "python", "app/init_db_clean.py"]