FROM debian:bullseye-slim

RUN apt-get update && \
    apt-get install -y curl jq netcat-openbsd && \
    rm -rf /var/lib/apt/lists/*


COPY scripts /scripts

RUN chmod +x /scripts/*.sh

ENTRYPOINT ["/scripts/wait-for-it.sh", "connect:8083", "--", "/scripts/wait-for-connect.sh", "connect", "8083", "/scripts/my_postgres_connector.json"]