FROM debian:bullseye-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl gettext-base jq && \
    rm -rf /var/lib/apt/lists/*


COPY scripts /scripts
COPY connector /connector

RUN chmod +x /scripts/*.sh

ENTRYPOINT ["/scripts/wait-for-connect.sh", "connect", "8083", "/connector/my_postgres_connector.json.template"]
